spring.application.name=GNSProject

server.forward-headers-strategy=framework

server.port=8080

# DB Configuration
# Native DB config of Spring Boot
#spring.datasource.url=${DB_URL:jdbc:postgresql://ep-quiet-wildflower-an4of1ki-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cRsQXSHeA07F&sslmode=require&channelBinding=require}
#spring.datasource.username= ${DB_USER:neondb_owner}
#spring.datasource.password= ${DB_PASS:npg_cRsQXSHeA07F}
#spring.datasource.driver-class-name= org.postgresql.Driver

#spring.datasource.url=${DB_URL:jdbc:postgresql://maglev.proxy.rlwy.net:34106/railway}
#spring.datasource.username=${DB_USER:postgres}
#spring.datasource.password=${DB_PASS:cBlSExRjEkwrWBSNPUdjHELyUvQbgvgV}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=default
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Mail Configuration
spring.mail.host=${SMTP_URL:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:ticket4naach@gmail.com}
spring.mail.password=${SMTP_PASSWORD:qtrrylmdhsavnpnn}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_TLS_ENABLE:true}

#Redis
spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true
