spring.application.name=GNSProject

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-quiet-wildflower-an4of1ki-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cRsQXSHeA07F&sslmode=require&channelBinding=require
spring.datasource.username= neondb_owner
spring.datasource.password= npg_cRsQXSHeA07F
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database=default
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Redis
#spring.data.redis.host=redis.railway.internal
#spring.data.redis.url=rediss://red-d796cm2a214c73alo7hg:OQUE6UlsV1nL0P5ga3D3bVH94NMF1Ksk@oregon-keyvalue.render.com:6379
#spring.data.redis.port=6379
#spring.data.redis.password=OQUE6UlsV1nL0P5ga3D3bVH94NMF1Ksk

spring.data.redis.host=oregon-keyvalue.render.com
spring.data.redis.port=6379
spring.data.redis.username=red-d796cm2a214c73alo7hg
spring.data.redis.password=OQUE6UlsV1nL0P5ga3D3bVH94NMF1Ksk
spring.data.redis.ssl=true


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ticket4naach@gmail.com
spring.mail.password=qtrr ylmd hsav npnn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
