spring.application.name=GNSProject

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.avglpnhuhqchsqicrefb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username= postgres
spring.datasource.password= HkxU2R4fr!7m4EjV
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database=default
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Redis
spring.data.redis.host=https://quick-sloth-78394.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAATI6AAIncDJmMjEyZTNhMTRjODI0YmFjYTg0Y2FkMDE5ZWJlODA5OXAyNzgzOTQ

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ticket4naach@gmail.com
spring.mail.password=qtrr ylmd hsav npnn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
